# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFWW931MxVCm4qfwxWa1crFPws6xMuu8
"""

import time
nu = 0
start = time.time()
print('이 프로그램은 계산기 프로그램 입니다')
print('첫번째 입력은 숫자를 입력하시고')
print('두번째 입력은 연산기호를')
print('세번쨰입력은 숫자를 입력하시면 됩니다')
print('들어갈수 있는 기호는 +,-,*,/,//,%입니다')
print('')
print('')
a = 1
while a == 1:
  n1 = int(input('숫자를 입력하세요:'))
  sign = input('기호를 입력하세요:')
  n2 = int(input('숫자를 입력하세요:'))
  if sign == '+':
    print('%d + %d = %d'%(n1,n2,n1 + n2))
  elif sign == '-':
    print('%d - %d = %d'%(n1,n2,n1 - n2))
  elif sign == '*':
    print('%d * %d = %d'%(n1,n2,n1 * n2))
  elif sign == '/':
    print('%d / %d = %d'%(n1,n2,n1 / n2))
  elif sign == '//':
    print('%d // %d = %d'%(n1,n2,n1 // n2))
  elif sign == '%':
    print('%d %% %d = %d'%(n1,n2,n1 % n2))
  nu = nu + 1
  print('현재까지 %d회 계산하셨습니다'%nu)
  a = int(input('계산을 종료하시려면 0을 아니라면 1을 눌러주세요'))

end = time.time()
print(end - start)